//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuArchiveEditor.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KungFuArchiveEditor.Assets.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ability name 的本地化字符串。
        /// </summary>
        public static string AbilityName {
            get {
                return ResourceManager.GetString("AbilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About the Matchless KungFu Archive Editor 的本地化字符串。
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 action 的本地化字符串。
        /// </summary>
        public static string ActionText {
            get {
                return ResourceManager.GetString("ActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 add addon property 的本地化字符串。
        /// </summary>
        public static string AddAddonProp {
            get {
                return ResourceManager.GetString("AddAddonProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 addon properties 的本地化字符串。
        /// </summary>
        public static string AddonProp {
            get {
                return ResourceManager.GetString("AddonProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please refer to the file for additional property ID: equip_addon_prop.txt 的本地化字符串。
        /// </summary>
        public static string AddonPropTip {
            get {
                return ResourceManager.GetString("AddonPropTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and property ID cannot be repeated 的本地化字符串。
        /// </summary>
        public static string AddonPropTip1 {
            get {
                return ResourceManager.GetString("AddonPropTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 amount 的本地化字符串。
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 anqi attack 的本地化字符串。
        /// </summary>
        public static string AnqiAttack {
            get {
                return ResourceManager.GetString("AnqiAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 archive file 的本地化字符串。
        /// </summary>
        public static string ArchiveFile {
            get {
                return ResourceManager.GetString("ArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 description 的本地化字符串。
        /// </summary>
        public static string AttrDescription {
            get {
                return ResourceManager.GetString("AttrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string AttrID {
            get {
                return ResourceManager.GetString("AttrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value 的本地化字符串。
        /// </summary>
        public static string AttrValue {
            get {
                return ResourceManager.GetString("AttrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bingqi attack 的本地化字符串。
        /// </summary>
        public static string BingqiAttack {
            get {
                return ResourceManager.GetString("BingqiAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cancel 的本地化字符串。
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 entity type 的本地化字符串。
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exp 的本地化字符串。
        /// </summary>
        public static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/liuguangw/KungFuArchiveEditor 的本地化字符串。
        /// </summary>
        public static string GitHubUrl {
            get {
                return ResourceManager.GetString("GitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hello 的本地化字符串。
        /// </summary>
        public static string HelloText {
            get {
                return ResourceManager.GetString("HelloText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 item name 的本地化字符串。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 position 的本地化字符串。
        /// </summary>
        public static string ItemPosition {
            get {
                return ResourceManager.GetString("ItemPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 level 的本地化字符串。
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 main property 的本地化字符串。
        /// </summary>
        public static string MainProp {
            get {
                return ResourceManager.GetString("MainProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Matchless KungFu Archive Editor 的本地化字符串。
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 max burden 的本地化字符串。
        /// </summary>
        public static string MaxBurden {
            get {
                return ResourceManager.GetString("MaxBurden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 max HP 的本地化字符串。
        /// </summary>
        public static string MaxHP {
            get {
                return ResourceManager.GetString("MaxHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 max zhenqi 的本地化字符串。
        /// </summary>
        public static string MaxZhenqi {
            get {
                return ResourceManager.GetString("MaxZhenqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _About 的本地化字符串。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Exit 的本地化字符串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open 的本地化字符串。
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 modify 的本地化字符串。
        /// </summary>
        public static string ModifyEquipment {
            get {
                return ResourceManager.GetString("ModifyEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name 的本地化字符串。
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ok 的本地化字符串。
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 open archive file 的本地化字符串。
        /// </summary>
        public static string OpenArchiveFile {
            get {
                return ResourceManager.GetString("OpenArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 quanfa attack 的本地化字符串。
        /// </summary>
        public static string QuanfaAttack {
            get {
                return ResourceManager.GetString("QuanfaAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rarity 的本地化字符串。
        /// </summary>
        public static string Rarity {
            get {
                return ResourceManager.GetString("Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save 的本地化字符串。
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 distribute items 的本地化字符串。
        /// </summary>
        public static string SendItemTitle {
            get {
                return ResourceManager.GetString("SendItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ability 的本地化字符串。
        /// </summary>
        public static string TabAbilityHeader {
            get {
                return ResourceManager.GetString("TabAbilityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bag 的本地化字符串。
        /// </summary>
        public static string TabBagHeader {
            get {
                return ResourceManager.GetString("TabBagHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        public static string TabRoleHeader {
            get {
                return ResourceManager.GetString("TabRoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tuifa attack 的本地化字符串。
        /// </summary>
        public static string TuifaAttack {
            get {
                return ResourceManager.GetString("TuifaAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 user id 的本地化字符串。
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zhangfa attack 的本地化字符串。
        /// </summary>
        public static string ZhangfaAttack {
            get {
                return ResourceManager.GetString("ZhangfaAttack", resourceCulture);
            }
        }
    }
}
